### ISSUE TITLE
Where is media supposed to go?

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [Floens/uchan#13]
The guide mentions all data goes in the /data folder which also contains a /media folder.
The config.ini also contains 2 lines for a tmp folder and a media folder.

I've defined a media folder (all rights for all users) and made /tmp the tmp folder.

Now I'm getting 
`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disk2/chanmedia/m9/6y2fk9ps56fcpx.jpg'
[2018-11-25 14:14:42,298] {app.py:1560} ERROR - Exception on /post [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./uchan/view/post.py", line 52, in post
    _upload_files(upload_queue_files_list)
  File "./uchan/view/post.py", line 213, in _upload_files
    file_service.do_upload(upload_queue_files)
  File "./uchan/lib/service/file_service.py", line 157, in do_upload
    cdn.upload(uploaded_file.image_output, uploaded_file.image_name)
  File "./uchan/lib/service/file_service.py", line 54, in upload
    shutil.copyfile(local_path, os.path.join(self.path, subdir, name))
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disk2/chanmedia/51/7yfwyr7fmazzx0.jpg'
[2018-11-25 14:14:42,299] {__init__.py:42} ERROR - [Errno 2] No such file or directory: '/mnt/disk2/chanmedia/51/7yfwyr7fmazzx0.jpg'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./uchan/view/post.py", line 52, in post
    _upload_files(upload_queue_files_list)
  File "./uchan/view/post.py", line 213, in _upload_files
    file_service.do_upload(upload_queue_files)
  File "./uchan/lib/service/file_service.py", line 157, in do_upload
    cdn.upload(uploaded_file.image_output, uploaded_file.image_name)
  File "./uchan/lib/service/file_service.py", line 54, in upload
    shutil.copyfile(local_path, os.path.join(self.path, subdir, name))
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disk2/chanmedia/51/7yfwyr7fmazzx0.jpg'
`
What could be wrong here?

**Comment by Floens** [comment]
When using `file_cdn_type = local`, the files when being uploaded are stored at `upload_queue_path` and then moved to `local_cdn_path`. Then, nginx has to be configured to serve files from `local_cdn_path` when the url starts with `local_cdn_web_path`.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
The properties in the config file were for the paths in docker.
Changed the docker-compose file to move the media folder.
Thanks.
