### ISSUE TITLE
No module names 'werkzeug.contrib'

### ISSUE THREAD

**Issue by DarkDeliver** [Floens/uchan#19]
A new bug appears after releasing werkzeug 1.0.0 (i think it's the reason), and uchan become uncompilable. After starting all services docker trying to launch app upgrade, but crushes. How can i fix it?
```
docker-compose run app upgrade
Traceback (most recent call last):
  File "/usr/bin/alembic", line 11, in <module>
    load_entry_point('alembic==0.8.8', 'console_scripts', 'alembic')()
  File "/usr/lib/python3.6/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python3.6/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python3.6/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/usr/lib/python3.6/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/lib/python3.6/site-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.6/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 17, in <module>
    from uchan.lib.database import OrmModelBase, connect_string
  File "/opt/app/uchan/__init__.py", line 142, in <module>
    init()
  File "/opt/app/uchan/__init__.py", line 51, in init
    from uchan.flask import create_web_app, CustomFlaskApp
  File "/opt/app/uchan/flask/__init__.py", line 4, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.contrib'
Makefile:15: recipe for target 'upgrade' failed
make: *** [upgrade] Error 1
```

**Comment by DarkDeliver** [comment]
Fix: just add `werkzeug==0.16.0` to the requirements file.
