### ISSUE TITLE
Assets container does not start, tsc command not found

### ISSUE THREAD

**Issue by alekratz** [Floens/uchan#24]
**I am using Docker on WSL2**, so take this report with a grain of salt.

I was following the setup instructions, and ran these commands:

```
make upgrade
make setup
```

and I create a new admin user.

When I try to pull up the site on localhost, I get this error:

># Server error
>The server encountered an error and could not complete the request.
>Please try again later.

I checked the `docker-compose ps` output, and I saw that the `assets` container has exited. Checking the logs gives me this message (I believe the first line is the root cause):

```
uchan-assets-1  | ./assets.sh: line 13: tsc: command not found
uchan-assets-1  |  * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
uchan-assets-1  | Building bundle: site.%(version)s.js
uchan-assets-1  | Building bundle: thread.%(version)s.js
uchan-assets-1  | Building bundle: extra.%(version)s.js
uchan-assets-1  | Failed, error was: [Errno 2] No such file or directory: '/opt/app/uchan/view/static/js/extra.js'
uchan-assets-1  | Building bundle: style.%(version)s.css
uchan-assets-1  | Traceback (most recent call last):
uchan-assets-1  |   File "/usr/bin/flask", line 11, in <module>
uchan-assets-1  |     sys.exit(main())
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/flask/cli.py", line 967, in main
uchan-assets-1  |     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/flask/cli.py", line 586, in main
uchan-assets-1  |     return super(FlaskGroup, self).main(*args, **kwargs)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/core.py", line 1053, in main
uchan-assets-1  |     rv = self.invoke(ctx)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
uchan-assets-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
uchan-assets-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
uchan-assets-1  |     return ctx.invoke(self.callback, **ctx.params)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/core.py", line 754, in invoke
uchan-assets-1  |     return __callback(*args, **kwargs)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
uchan-assets-1  |     return f(get_current_context(), *args, **kwargs)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
uchan-assets-1  |     return __ctx.invoke(f, *args, **kwargs)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/click/core.py", line 754, in invoke
uchan-assets-1  |     return __callback(*args, **kwargs)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/flask_assets.py", line 492, in build
uchan-assets-1  |     _webassets_cmd('build')
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/flask_assets.py", line 480, in _webassets_cmd
uchan-assets-1  |     getattr(cmdenv, cmd)()
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/script.py", line 172, in __call__
uchan-assets-1  |     bundle.build(force=True, disable_cache=no_cache)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/bundle.py", line 683, in build
uchan-assets-1  |     disable_cache=disable_cache))
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/bundle.py", line 620, in _build
uchan-assets-1  |     force, disable_cache=disable_cache, extra_filters=extra_filters)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/bundle.py", line 544, in _merge_and_apply
uchan-assets-1  |     kwargs=item_data)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/merge.py", line 280, in apply
uchan-assets-1  |     return self._wrap_cache(key, func)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/merge.py", line 222, in _wrap_cache
uchan-assets-1  |     content = func().getvalue()
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/merge.py", line 255, in func
uchan-assets-1  |     getattr(filter, type)(data, out, **kwargs_final)
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/filter/cleancss.py", line 45, in input
uchan-assets-1  |     if self.cleancss_ver < 4:
uchan-assets-1  |   File "/usr/lib/python3.6/site-packages/webassets/filter/cleancss.py", line 33, in cleancss_ver
uchan-assets-1  |     out, err = Popen(args, stdout=PIPE).communicate()
uchan-assets-1  |   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
uchan-assets-1  |     restore_signals, start_new_session)
uchan-assets-1  |   File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
uchan-assets-1  |     raise child_exception_type(errno_num, err_msg, err_filename)
uchan-assets-1  | FileNotFoundError: [Errno 2] No such file or directory: 'cleancss': 'cleancss'
```

Ultimately, the `assets` container is unable to find the `tsc` executable for Typescript. Inside a `docker-compose exec app /bin/sh` when I try to run anything with `npm` it gives me this error:

```
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Since this command exits with error code 0, it allows Docker to silently continue as if no errors occurred. This uid/gid error looks like it may be related to WSL2 and Docker, but I'm not 100% sure. It may have been fixed in a later version of the nodejs package, according to this Stackoverflow thread: https://stackoverflow.com/questions/52196518/could-not-get-uid-gid-when-building-node-docker

Is this something that you're able to reproduce on Linux? I don't have a Linux machine handy right now. I may play around with upgrading the version of Alpine and seeing if that fixes anything.

**Comment by alekratz** [comment]
This seems to have been a Docker on WSL2 issue, I'm at a Linux machine now and I'm not running into this problem.

**Comment by successor1** [comment]
same on Macos
